### ISSUE TITLE
Failed to run MiniHack Experiments (Environments not found)

### ISSUE THREAD

**Issue by azadsalam** [ucl-dark/paired#3]
I am trying to run the MiniHack experiments with the following command:

```
python -m train \
--xpid=ued-MiniHack-GoalLastAdv-WallsLavaMonsterDoor-15x15-v0-paired-lstm256a-lr0.0001-epoch5-mb1-v0.5-henv0.0-ha0.0-tl_0 \
--env_name=MiniHack-GoalLastAdv-WallsLavaMonsterDoor-15x15-v0 \
--use_gae=True \
--gamma=0.995 \
--gae_lambda=0.95 \
--seed=88 \
--recurrent_arch=lstm \
--recurrent_agent=True \
--recurrent_adversary_env=False \
--recurrent_hidden_size=256 \
--lr=0.0001 \
--num_steps=256 \
--num_processes=4 \
--num_env_steps=100000 \
--ppo_epoch=5 \
--num_mini_batch=1 \
--entropy_coef=0.0 \
--value_loss_coef=0.5 \
--clip_param=0.2 \
--clip_value_loss=True \
--adv_entropy_coef=0.0 \
--algo=ppo \
--ued_algo=paired \
--log_interval=10 \
--screenshot_interval=1000 \
--log_grad_norm=True \
--handle_timelimits=True \
--test_env_names=MiniHack-Room-15x15-v0,MiniHack-Room-Monster-15x15-v0,MiniHack-MazeWalk-9x9-v0,MiniHack-MazeWalk-15x15-v0,MiniHack-Labyrinth-Small-v0,MiniHack-LockedMultiRoom-N2-S4-v0,MiniHack-LavaMultiRoom-N2-S4-v0,MiniHack-MonsterMultiRoom-N2-S4-v0,MiniHack-ExtremeMultiRoom-N2-S4-v0,MiniHack-ExtremeMultiRoom-N4-S5-v0 \
--log_dir=logs/paired/minihack \
--log_action_complexity=True \
--checkpoint=True
``` 

I am receiving errors of the following kind:
```
gym.error.UnregisteredEnv: No registered env with id: MiniHack-LockedMultiRoom-N2-S4-v0 
```

I searched the codebase but did not find any matches with the string "MiniHack-LockedMultiRoom-N2-S4-v0".   Any idea how to solve this?  

The error is  originating from [Line 133 envs/register.py](https://github.com/ucl-dark/paired/blob/master/envs/registration.py#L132), because no MiniHack environments was registered via [EnvRegistry.register()](https://github.com/ucl-dark/paired/blob/master/envs/registration.py#L144)

**Comment by minqi** [comment]
Hi Azad, 

It looks like the latest version of MiniHack removed these environments. My local copy of MiniHack has this environment, and its version information is

```
__version__ = '0.1.0b+931bb48'
git_version = '931bb4897927c519a8332bf8bab8ff7433a1237e'
```

cc @samvelyan, who would be able to add more context regarding this change.

**Comment by samvelyan** [comment]
Hi Azad and Minqi,

Yes, we have slighly updated the names of the MiniGrid environments in MiniHack. The current names can be found here: https://minihack.readthedocs.io/en/latest/envs/ported/minigrid.html.

Hope this helps.

**Comment by azadsalam** [comment]
Thank you for your feedback!

I think the following renaming has to be done for the paired experiments for MiniHack v 0.1.3: 

Old Name                                                                       New Name
-------------------------------------------------------------------------------------
MiniHack-MultiRoom-N2-S4-v0,                   =>           MiniHack-MultiRoom-N2-v0
MiniHack-LockedMultiRoom-N2-S4-v0,       =>           MiniHack-MultiRoom-N2-Locked-v0
MiniHack-LavaMultiRoom-N2-S4-v0,           =>           MiniHack-MultiRoom-N2-Lava-v0
MiniHack-MonsterMultiRoom-N2-S4-v0,     =>           MiniHack-MultiRoom-N2-Monster-v0
MiniHack-ExtremeMultiRoom-N2-S4-v0,     =>           MiniHack-MultiRoom-N2-Extreme-v0
MiniHack-ExtremeMultiRoom-N4-S5-v0      =>           MiniHack-MultiRoom-N4-v0
